
--Q1. What is the total revenue generated by male vs. female customers?
--ingreso total generado por las personas masculinas respecto a las mujeres
select sexo, SUM(monto_de_compre) as revenue
from cliente
group by sexo


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
--que cliente usaron un decuento pero aun asi gastaron mas que el monto promedio de compra
select idcliente, monto_de_compre 
from cliente 
where descuento_aplicado = 'Yes' and monto_de_compre >= (select AVG(monto_de_compre) from cliente)


-- Q3. Which are the top 5 products with the highest average review rating?
--5 productos productos mporincipales mejor valorados o comentados por los clientes
SELECT TOP 5
       articulo_comprado,
       ROUND(AVG(CAST(calificacion_del_cliente AS DECIMAL(10,2))), 2) AS [Promedio Calificacion del producto]
FROM cliente
GROUP BY articulo_comprado
ORDER BY AVG(CAST(calificacion_del_cliente AS DECIMAL(10,2))) DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
--comparar el importe mediod e comprar entre el envio estandar y express
select tipo_de_envio, 
ROUND(AVG(monto_de_compre),2) as Promedio_monto_de_compra
from cliente
where tipo_de_envio in ('Standard','Express')
group by tipo_de_envio;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
----compara el gasto medio e ingresos totales entre suscriptores y no suscriptores
SELECT estado_de_suscripcion,
       COUNT(idcliente) AS total_de_clientes,
       ROUND(AVG(monto_de_compre),2) AS Gastomedio,
       ROUND(SUM(monto_de_compre),2) AS ingresototal
FROM cliente
GROUP BY estado_de_suscripcion
ORDER BY ingresototal,Gastomedio DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--que 5 productos tienen el mayor porcentaje de compras con dscto aplicados


SELECT TOP 5
       articulo_comprado,
       ROUND(
           100.0 * SUM(CASE WHEN descuento_aplicado = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
           2
       ) AS Tasa_de_descuento
FROM cliente
GROUP BY articulo_comprado
ORDER BY Tasa_de_descuento DESC;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
--segmentar a los clientes en nuevos recurrentes y leales segun sus compras realizadas
--
with tipo_cliente as (
SELECT idcliente, compras_anteriores,
CASE 
    WHEN compras_anteriores = 1 THEN 'Nuevo'
    WHEN compras_anteriores BETWEEN 2 AND 10 THEN 'Recurrente'
    ELSE 'Leal'
    END AS Segmento_CLiente
FROM cliente)

select Segmento_CLiente,count(*) AS "Numero de clientes" 
from tipo_cliente 
group by Segmento_CLiente;

--8. Los 3 mejores productos por categoría – Listado de los productos más
--comprados en cada categoría.


WITH CUENTADEARTICULOS AS(
SELECT CATEGORIA,
       ARTICULO_COMPRADO,
	   COUNT(IDCLIENTE) AS TOTAL_DE_PEDIDOS,
	   ROW_NUMBER() OVER(PARTITION BY CATEGORIA ORDER BY COUNT(IDCLIENTE) DESC) AS RANKING_DE_PRODUCTOS
FROM CLIENTE
GROUP BY CATEGORIA,ARTICULO_COMPRADO

)
SELECT RANKING_DE_PRODUCTOS,CATEGORIA,ARTICULO_COMPRADO,TOTAL_DE_PEDIDOS
FROM CUENTADEARTICULOS
WHERE RANKING_DE_PRODUCTOS<=3



--9. Clientes recurrentes y suscripciones – Análisis de si los clientes con más de
--5 compras tienen mayor probabilidad de suscribirse

select estado_de_suscripcion,
       count(idcliente) as Compras_recurrentes
from cliente
where compras_anteriores>5
group by estado_de_suscripcion